### ISSUE TITLE
500 internal server error when installing plugin

### ISSUE THREAD

**Issue by Floriskoch** [skydiver/october-plugin-sentryerrorlogger#2]
Hi there, 

I'm getting a 500 internal server error when installing plugin. It seems that it has something to do with the composer packages but I haven't discovered the exact culprit.

I tried running `composer update` in the plugin folder but that did not resolve the problem either.

**Comment by CptMeatball** [comment]
This is is resolved by updating the composer.json sentry dependency to 0.8.0.

**Comment by skydiver** [comment]
Great @CptMeatball 

Thanks a lot, i'll be pushing to October marketplace
